import type { Locale } from "@/lib/i18n";

export const licenseCopy = {
  vi: {
    title: "Giấy phép máy chủ",
    desc: "Kích hoạt giấy phép cho máy chủ bằng SDK từ repo License-Key.",
    activationTitle: "Kích hoạt giấy phép",
    activationDesc: "Xuất tệp thông tin cấp giấy phép, gửi nhà cung cấp và nhập tệp giấy phép đã được cấp để tiếp tục.",
    checkingTitle: "Đang kiểm tra giấy phép",
    checkingDesc: "Ứng dụng sẽ chỉ mở tiếp khi giấy phép máy chủ hợp lệ.",
    requiredTitle: "Cần kích hoạt giấy phép",
    requiredDesc: "Giấy phép máy chủ chưa hợp lệ. Hãy nhập giấy phép để tiếp tục.",
    refresh: "Kiểm tra",
    exportInfo: "Xuất thông tin",
    copyMachine: "Sao chép mã máy",
    importFile: "Chọn tệp giấy phép",
    activate: "Kích hoạt",
    activating: "Đang kích hoạt",
    exportStepTitle: "1. Xuất thông tin cấp giấy phép",
    exportStepDesc: "Tệp JSON gồm machine_id, product, app_version và release_date.",
    importStepTitle: "2. Nhập tệp giấy phép",
    importStepDesc: "Chọn tệp hoặc dán chuỗi giấy phép đã được ký.",
    machineId: "Mã máy",
    product: "Sản phẩm",
    version: "Phiên bản",
    releaseDate: "Ngày phát hành",
    licensePath: "Nơi lưu giấy phép",
    customer: "Khách hàng",
    project: "Dự án",
    updateUntil: "Cập nhật đến",
    expiresAt: "Hết hạn",
    status: "Trạng thái",
    active: "Đã kích hoạt",
    unactivated: "Chưa kích hoạt",
    invalid: "Giấy phép lỗi",
    unavailable: "Chức năng giấy phép chỉ hoạt động trong ứng dụng desktop Electron.",
    loadFailed: "Không tải được trạng thái giấy phép.",
    fileReadFailed: "Không đọc được tệp giấy phép.",
    missingLicense: "Chọn tệp hoặc dán chuỗi giấy phép trước.",
    copied: "Đã sao chép mã máy.",
    exported: "Đã xuất tệp thông tin cấp giấy phép.",
    activated: "Giấy phép đã kích hoạt.",
    activateFailed: "Giấy phép không hợp lệ.",
    returnedToActivation: "Giấy phép không còn hợp lệ. Ứng dụng đã quay về màn kích hoạt.",
    placeholder: "Dán chuỗi giấy phép đã được nhà cung cấp ký...",
    sdkSource: "Nguồn SDK",
    sdkSourceValue: "external/license-key"
  },
  en: {
    title: "Server license",
    desc: "Activate the server machine license through the License-Key SDK repository.",
    activationTitle: "Activate license",
    activationDesc: "Export the license request file, send it to the vendor, then import the issued license file to continue.",
    checkingTitle: "Checking license",
    checkingDesc: "The app will continue only when the server license is valid.",
    requiredTitle: "License activation required",
    requiredDesc: "The server license is not valid. Import a license to continue.",
    refresh: "Check",
    exportInfo: "Export info",
    copyMachine: "Copy machine ID",
    importFile: "Choose license file",
    activate: "Activate",
    activating: "Activating",
    exportStepTitle: "1. Export license info",
    exportStepDesc: "The JSON file includes machine_id, product, app_version, and release_date.",
    importStepTitle: "2. Import license file",
    importStepDesc: "Choose a file or paste the signed license string.",
    machineId: "Machine ID",
    product: "Product",
    version: "Version",
    releaseDate: "Release date",
    licensePath: "License path",
    customer: "Customer",
    project: "Project",
    updateUntil: "Update until",
    expiresAt: "Expires at",
    status: "Status",
    active: "Active",
    unactivated: "Unactivated",
    invalid: "Invalid license",
    unavailable: "License management is only available in Electron desktop.",
    loadFailed: "Unable to load license status.",
    fileReadFailed: "Unable to read license file.",
    missingLicense: "Choose a file or paste the license string first.",
    copied: "Machine ID copied.",
    exported: "License request info exported.",
    activated: "License activated.",
    activateFailed: "Invalid license.",
    returnedToActivation: "The license is no longer valid. The app returned to activation.",
    placeholder: "Paste the signed license string...",
    sdkSource: "SDK source",
    sdkSourceValue: "external/license-key"
  }
} as const;

export function getLicenseCopy(locale: Locale) {
  return licenseCopy[locale];
}
