import type { Locale } from "@/lib/i18n";

export const licenseCopy = {
  vi: {
    title: "License máy server",
    desc: "Kích hoạt license cho máy server bằng SDK từ repo License-Key.",
    activationTitle: "Kích hoạt license",
    activationDesc: "Xuất file thông tin cấp license, gửi nhà cung cấp và nhập file license đã được cấp để tiếp tục.",
    checkingTitle: "Đang kiểm tra license",
    checkingDesc: "Ứng dụng sẽ chỉ mở tiếp khi license server hợp lệ.",
    requiredTitle: "Cần kích hoạt license",
    requiredDesc: "License server chưa hợp lệ. Hãy nhập license để tiếp tục.",
    refresh: "Kiểm tra",
    exportInfo: "Xuất thông tin",
    copyMachine: "Copy mã máy",
    importFile: "Chọn file license",
    activate: "Kích hoạt",
    activating: "Đang kích hoạt",
    exportStepTitle: "1. Xuất thông tin cấp license",
    exportStepDesc: "File JSON gồm machine_id, product, app_version và release_date.",
    importStepTitle: "2. Nhập file license",
    importStepDesc: "Chọn file hoặc dán chuỗi license đã được ký.",
    machineId: "Mã máy",
    product: "Product",
    version: "Phiên bản",
    releaseDate: "Ngày release",
    licensePath: "Nơi lưu license",
    customer: "Khách hàng",
    project: "Dự án",
    updateUntil: "Update đến",
    expiresAt: "Hết hạn",
    status: "Trạng thái",
    active: "Đã kích hoạt",
    unactivated: "Chưa kích hoạt",
    invalid: "License lỗi",
    unavailable: "Chức năng license chỉ hoạt động trong Electron desktop.",
    loadFailed: "Không tải được trạng thái license.",
    fileReadFailed: "Không đọc được file license.",
    missingLicense: "Chọn file hoặc dán chuỗi license trước.",
    copied: "Đã copy mã máy.",
    exported: "Đã xuất file thông tin cấp license.",
    activated: "License đã kích hoạt.",
    activateFailed: "License không hợp lệ.",
    returnedToActivation: "License không còn hợp lệ. Ứng dụng đã quay về màn kích hoạt.",
    placeholder: "Dán chuỗi license đã được nhà cung cấp ký...",
    sdkSource: "Nguồn SDK",
    sdkSourceValue: "external/license-key"
  },
  en: {
    title: "Server license",
    desc: "Activate the server machine license through the License-Key SDK repository.",
    activationTitle: "Activate license",
    activationDesc: "Export the license request file, send it to the vendor, then import the issued license file to continue.",
    checkingTitle: "Checking license",
    checkingDesc: "The app will continue only when the server license is valid.",
    requiredTitle: "License activation required",
    requiredDesc: "The server license is not valid. Import a license to continue.",
    refresh: "Check",
    exportInfo: "Export info",
    copyMachine: "Copy machine ID",
    importFile: "Choose license file",
    activate: "Activate",
    activating: "Activating",
    exportStepTitle: "1. Export license info",
    exportStepDesc: "The JSON file includes machine_id, product, app_version, and release_date.",
    importStepTitle: "2. Import license file",
    importStepDesc: "Choose a file or paste the signed license string.",
    machineId: "Machine ID",
    product: "Product",
    version: "Version",
    releaseDate: "Release date",
    licensePath: "License path",
    customer: "Customer",
    project: "Project",
    updateUntil: "Update until",
    expiresAt: "Expires at",
    status: "Status",
    active: "Active",
    unactivated: "Unactivated",
    invalid: "Invalid license",
    unavailable: "License management is only available in Electron desktop.",
    loadFailed: "Unable to load license status.",
    fileReadFailed: "Unable to read license file.",
    missingLicense: "Choose a file or paste the license string first.",
    copied: "Machine ID copied.",
    exported: "License request info exported.",
    activated: "License activated.",
    activateFailed: "Invalid license.",
    returnedToActivation: "The license is no longer valid. The app returned to activation.",
    placeholder: "Paste the signed license string...",
    sdkSource: "SDK source",
    sdkSourceValue: "external/license-key"
  }
} as const;

export function getLicenseCopy(locale: Locale) {
  return licenseCopy[locale];
}
