export const SUPPORTED_LOCALES = ["vi", "en"] as const;
export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

export const SUPPORTED_THEMES = ["light", "dark"] as const;
export type SupportedTheme = (typeof SUPPORTED_THEMES)[number];

export const SCAN_STATUS = {
  OK: "OK",
  NG: "NG",
  PENDING: "PENDING",
  SKIPPED: "SKIPPED"
} as const;

export const ERROR_CODES = {
  LOCAL_DUPLICATE: "LOCAL_DUPLICATE",
  FULL_CODE_INVALID_LENGTH: "FULL_CODE_INVALID_LENGTH",
  FULL_VENDOR_NOT_MATCH: "FULL_VENDOR_NOT_MATCH",
  FULL_FACTORY_NOT_MATCH: "FULL_FACTORY_NOT_MATCH",
  CHASSIS_NOT_MATCH: "CHASSIS_NOT_MATCH",
  LED_VENDOR_NOT_MATCH: "LED_VENDOR_NOT_MATCH",
  LED_SUFFIX_NOT_MATCH: "LED_SUFFIX_NOT_MATCH",
  SERVER_DUPLICATE: "SERVER_DUPLICATE",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  MACHINE_NOT_FOUND: "MACHINE_NOT_FOUND",
  PROFILE_VERSION_OUTDATED: "PROFILE_VERSION_OUTDATED",
  SERVER_DISCONNECTED: "SERVER_DISCONNECTED",
  SYNC_BATCH_HAS_NG: "SYNC_BATCH_HAS_NG",
  PAYLOAD_INVALID: "PAYLOAD_INVALID"
} as const;

export const NOTIFICATION_CODES = {
  LOCAL_SERVER_OFFLINE: "LOCAL_SERVER_OFFLINE",
  LOCAL_SERVER_RECONNECTED: "LOCAL_SERVER_RECONNECTED",
  OFFLINE_SYNC_DONE_OK: "OFFLINE_SYNC_DONE_OK",
  OFFLINE_SYNC_HAS_NG: "OFFLINE_SYNC_HAS_NG",
  MACHINE_OFFLINE: "MACHINE_OFFLINE",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  DUPLICATE_REPORT_READY: "DUPLICATE_REPORT_READY"
} as const;

export type ApiResponse<T> = {
  success: boolean;
  code: string;
  message: string;
  data?: T;
};

export type ScanDecision =
  | "LOCAL_NG_SAVED"
  | "SERVER_OK"
  | "SERVER_DUPLICATE";
